name: Tag Experiment After PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag-experiment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and Push Tag
        run: |
          # Create a tag based on the PR title or experiment number
          EXPERIMENT_TAG="experiment-$(date +'%Y%m%d')-${{ github.event.pull_request.number }}"
          
          # Create the tag and push it to the remote
          git tag $EXPERIMENT_TAG
          git push origin $EXPERIMENT_TAG
          
          echo "Tagged the experiment with $EXPERIMENT_TAG"
